# Generated by Django 6.0.1 on 2026-01-26 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shiftApp', '0001_initial'),
        ('taskApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTaskRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation_interval_minutes', models.IntegerField(default=60, help_text='Minutes each employee works on a task before rotating')),
                ('is_active', models.BooleanField(default=True)),
                ('allow_multiple_employees_per_task', models.BooleanField(default=False, help_text='Allow multiple employees on same task for overload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotations_created', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_rotations', to='shiftApp.shift')),
                ('tasks', models.ManyToManyField(help_text='Tasks to rotate through during this shift', related_name='shift_rotations', to='taskApp.task')),
            ],
            options={
                'verbose_name': 'Shift Task Rotation',
                'verbose_name_plural': 'Shift Task Rotations',
            },
        ),
        migrations.CreateModel(
            name='TaskOverload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overload_date', models.DateField()),
                ('additional_employees_needed', models.IntegerField(default=1, help_text='Additional employees needed beyond normal rotation')),
                ('time_slot_start', models.TimeField(blank=True, help_text='Specific time slot start (optional)', null=True)),
                ('time_slot_end', models.TimeField(blank=True, help_text='Specific time slot end (optional)', null=True)),
                ('reason', models.TextField(help_text='Reason for overload')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overloads_created', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_overloads', to='shiftApp.shift')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overloads', to='taskApp.task')),
            ],
            options={
                'verbose_name': 'Task Overload',
                'verbose_name_plural': 'Task Overloads',
                'ordering': ['-overload_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField(help_text='Date of the assignment')),
                ('start_time', models.DateTimeField(help_text='When employee should start this task')),
                ('end_time', models.DateTimeField(help_text='When employee should finish this task')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('missed', 'Missed'), ('reassigned', 'Reassigned')], default='scheduled', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('sequence_order', models.IntegerField(default=0, help_text="Order of this task in employee's daily rotation")),
                ('is_modified', models.BooleanField(default=False, help_text='True if assignment was manually modified by admin/supervisor')),
                ('modification_reason', models.TextField(blank=True, help_text='Reason for manual modification', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_modified', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='shiftApp.shift')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='taskApp.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task Assignment',
                'verbose_name_plural': 'Task Assignments',
                'ordering': ['assignment_date', 'start_time', 'sequence_order'],
                'indexes': [models.Index(fields=['user', 'assignment_date', 'status'], name='taskAssignm_user_id_cf5740_idx'), models.Index(fields=['assignment_date', 'start_time'], name='taskAssignm_assignm_0dfcdc_idx'), models.Index(fields=['status', 'start_time'], name='taskAssignm_status_98ef88_idx')],
                'unique_together': {('user', 'assignment_date', 'sequence_order')},
            },
        ),
    ]
