# Generated by Django 6.0.1 on 2026-01-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskAssignmentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Store tracking data like sent reminders'),
        ),
    ]
