# Generated by Django 6.0.1 on 2026-01-26 08:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('performanceApp', '0001_initial'),
        ('shiftApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('emp_number', models.CharField(max_length=50, unique=True, verbose_name='Employee Number')),
                ('names', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.BinaryField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('employee', 'Employee')], default='employee', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='prefer_not_to_say', max_length=20)),
                ('day_off', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('none', 'No Day Off')], default='none', max_length=20, verbose_name='Weekly Day Off')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('current_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='shiftApp.shift')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('supervisors', models.ManyToManyField(blank=True, limit_choices_to={'role': 'supervisor'}, related_name='supervised_employees', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('break_start', 'Break Start'), ('break_end', 'Break End'), ('shift_start', 'Shift Start'), ('shift_end', 'Shift End'), ('system_event', 'System Event')], max_length=20)),
                ('status', models.CharField(choices=[('early', 'Early'), ('on_time', 'On Time'), ('late', 'Late'), ('very_late', 'Very Late'), ('absent', 'Absent'), ('day_off', 'Day Off'), ('system_auto', 'System Auto'), ('manual', 'Manual')], max_length=20)),
                ('activity', models.CharField(help_text='Description of the activity', max_length=255)),
                ('system_generated_reason', models.TextField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, help_text='When it was supposed to happen', null=True)),
                ('actual_time', models.DateTimeField(auto_now_add=True, help_text='When it actually happened')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('break_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_logs', to='performanceApp.breaklog')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_logs', to='shiftApp.shift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Log',
                'verbose_name_plural': 'User Logs',
                'ordering': ['-actual_time'],
                'indexes': [models.Index(fields=['user', 'log_type', 'actual_time'], name='userApp_use_user_id_f6c051_idx'), models.Index(fields=['user', 'created_at'], name='userApp_use_user_id_1b5a4b_idx'), models.Index(fields=['log_type', 'status'], name='userApp_use_log_typ_74bad3_idx')],
            },
        ),
    ]
