# Generated by Django 6.0.1 on 2026-01-26 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Morning Shift, Night Shift', max_length=200)),
                ('start_at', models.TimeField(help_text='Time when shift starts (e.g., 08:00)')),
                ('end_at', models.TimeField(help_text='Time when shift ends (e.g., 16:00)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='BreakTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Lunch Break, Tea Break', max_length=200)),
                ('start_at', models.TimeField(help_text='Time when break starts (e.g., 12:00)')),
                ('end_at', models.TimeField(help_text='Time when break ends (e.g., 13:00)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='shiftApp.shift')),
            ],
            options={
                'verbose_name': 'Break Template',
                'verbose_name_plural': 'Break Templates',
                'ordering': ['shift', 'start_at'],
                'unique_together': {('shift', 'name')},
            },
        ),
    ]
