# Generated by Django 6.0.1 on 2026-01-26 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performanceApp', '__first__'),
        ('userApp', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_start_reminder', models.BooleanField(default=True)),
                ('break_start_reminder_minutes', models.IntegerField(default=5, help_text='Minutes before break start')),
                ('break_end_reminder', models.BooleanField(default=True)),
                ('break_end_reminder_minutes', models.IntegerField(default=5, help_text='Minutes before break end')),
                ('break_missed_alert', models.BooleanField(default=True)),
                ('break_extended_alert', models.BooleanField(default=True)),
                ('shift_start_reminder', models.BooleanField(default=True)),
                ('shift_start_reminder_minutes', models.IntegerField(default=15, help_text='Minutes before shift start')),
                ('shift_end_reminder', models.BooleanField(default=True)),
                ('shift_end_reminder_minutes', models.IntegerField(default=15, help_text='Minutes before shift end')),
                ('login_reminder', models.BooleanField(default=True)),
                ('logout_reminder', models.BooleanField(default=True)),
                ('system_alerts', models.BooleanField(default=True)),
                ('performance_alerts', models.BooleanField(default=True)),
                ('web_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=False)),
                ('dnd_enabled', models.BooleanField(default=False)),
                ('dnd_start_time', models.TimeField(blank=True, null=True)),
                ('dnd_end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('break_start_reminder', 'Break Start Reminder'), ('break_end_reminder', 'Break End Reminder'), ('break_missed', 'Break Missed'), ('break_extended', 'Break Extended'), ('shift_start_reminder', 'Shift Start Reminder'), ('shift_end_reminder', 'Shift End Reminder'), ('login_reminder', 'Login Reminder'), ('logout_reminder', 'Logout Reminder'), ('system_alert', 'System Alert'), ('performance_alert', 'Performance Alert')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('action_text', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When notification becomes irrelevant', null=True)),
                ('break_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='performanceApp.breaklog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('user_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='userApp.userlog')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_58247f_idx'), models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_ddbc1e_idx'), models.Index(fields=['user', 'notification_type', 'is_read'], name='notificatio_user_id_669a85_idx')],
            },
        ),
    ]
