# Generated by Django 6.0.1 on 2026-01-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='task_end_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='task_end_reminder_minutes',
            field=models.IntegerField(default=5, help_text='Minutes before task end'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='task_missed_alerts',
            field=models.BooleanField(default=True, help_text='Receive alerts for missed tasks'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='upcoming_task_alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('break_start_reminder', 'Break Start Reminder'), ('break_end_reminder', 'Break End Reminder'), ('break_missed', 'Break Missed'), ('break_extended', 'Break Extended'), ('shift_start_reminder', 'Shift Start Reminder'), ('shift_end_reminder', 'Shift End Reminder'), ('login_reminder', 'Login Reminder'), ('logout_reminder', 'Logout Reminder'), ('system_alert', 'System Alert'), ('performance_alert', 'Performance Alert'), ('task_end_reminder', 'Task End Reminder'), ('task_missed_alert', 'Task Missed Alert'), ('upcoming_task_alert', 'Upcoming Task Alert')], max_length=50),
        ),
    ]
