# Generated by Django 6.0.1 on 2026-01-26 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shiftApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('started', 'Started'), ('completed', 'Completed'), ('missed', 'Missed'), ('extended', 'Extended'), ('shortened', 'Shortened')], default='scheduled', max_length=20)),
                ('start_punctuality', models.CharField(blank=True, choices=[('early', 'Early'), ('on_time', 'On Time'), ('late', 'Late')], max_length=20, null=True)),
                ('end_punctuality', models.CharField(blank=True, choices=[('early', 'Early'), ('on_time', 'On Time'), ('late', 'Late')], max_length=20, null=True)),
                ('system_generated_reason', models.TextField(blank=True, null=True)),
                ('is_auto_recorded', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('was_user_logged_in', models.BooleanField(default=False, help_text='Whether user was logged in when break started')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('break_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_logs', to='shiftApp.breaktemplate')),
            ],
            options={
                'verbose_name': 'Break Log',
                'verbose_name_plural': 'Break Logs',
                'ordering': ['scheduled_start'],
            },
        ),
    ]
