# export_utils.py
import pandas as pd
import json
from io import BytesIO, StringIO
from django.http import HttpResponse
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.units import inch
from django.utils.timezone import now
import csv
from reportlab.platypus import KeepTogether
from reportlab.platypus import BaseDocTemplate, Frame, PageTemplate

# At the top of export_utils.py
import pandas as pd
import json
from io import BytesIO, StringIO
from django.http import HttpResponse
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.units import inch
from django.utils.timezone import now
import csv
from reportlab.platypus import KeepTogether
from reportlab.platypus import BaseDocTemplate, Frame, PageTemplate

class ReportExporter:
    """Utility class for exporting reports in various formats"""
    
    @staticmethod
    def export_pdf(report_type, report_data, filters, config, user):
        """Export report as PDF with both summary and detailed data"""
        try:
            # Create buffer for PDF
            buffer = BytesIO()
            doc = SimpleDocTemplate(buffer, pagesize=letter)
            elements = []
            styles = getSampleStyleSheet()
            
            # Header
            title = config.get('title', f'{report_type.capitalize()} Report')
            elements.append(Paragraph(title, styles['Title']))
            elements.append(Spacer(1, 12))
            
            # Report Info
            info_text = f"""
            <b>Organization:</b> {config.get('organization', 'Employee Management System')}<br/>
            <b>System:</b> {config.get('system', 'Shift & Task Management System')}<br/>
            <b>Generated By:</b> {config.get('generated_by', user.names if hasattr(user, 'names') else 'System')}<br/>
            <b>Generated At:</b> {now().strftime('%Y-%m-%d %H:%M:%S')}<br/>
            <b>Report Type:</b> {report_type.replace('_', ' ').title()}<br/>
            <b>Export Format:</b> PDF<br/>
            """
            elements.append(Paragraph(info_text, styles['Normal']))
            elements.append(Spacer(1, 20))
            
            # Filters Section
            if filters:
                filter_text = "<b>Filters Applied:</b><br/>"
                for key, value in filters.items():
                    if value:
                        filter_text += f"- {key.replace('_', ' ').title()}: {value}<br/>"
                elements.append(Paragraph(filter_text, styles['Normal']))
                elements.append(Spacer(1, 20))
            
            # SECTION 1: SUMMARY DATA
            elements.append(Paragraph("<b>1. REPORT SUMMARY</b>", styles['Heading2']))
            elements.append(Spacer(1, 10))
            
            if report_data.get('summary'):
                summary = report_data['summary']
                
                # Create summary table
                summary_data = [['Metric', 'Value']]
                
                if report_type == 'admin_dashboard':
                    summary_data.extend([
                        ['Total Users', summary.get('users', {}).get('total', 0)],
                        ['Active Users', summary.get('users', {}).get('active', 0)],
                        ['Total Shifts', summary.get('shifts', {}).get('total', 0)],
                        ['Total Tasks', summary.get('tasks', {}).get('total', 0)],
                        ['Pending Requests', summary.get('requests', {}).get('pending', 0)]
                    ])
                elif report_type == 'user_analytics':
                    summary_data.extend([
                        ['Total Users', summary.get('total_users', 0)],
                        ['Active Today', summary.get('active_today', 0)],
                        ['Recent Registrations', summary.get('recent_registrations', 0)],
                        ['Average Salary', f"${summary.get('average_salary', 0):,.2f}"]
                    ])
                elif report_type == 'team_performance':
                    summary_data.extend([
                        ['Team Members', summary.get('total_employees', 0)],
                        ['Supervisor', summary.get('supervisor_name', '')],
                        ['Time Period', summary.get('time_period', '')]
                    ])
                
                if len(summary_data) > 1:
                    table = Table(summary_data, colWidths=[3*inch, 2*inch])
                    table.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#2E86C1')),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                        ('FONTSIZE', (0, 0), (-1, 0), 11),
                        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#F2F3F4')),
                        ('GRID', (0, 0), (-1, -1), 1, colors.black),
                        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F9F9F9')])
                    ]))
                    elements.append(table)
                    elements.append(Spacer(1, 20))
            
            # SECTION 2: DETAILED DATA
            elements.append(Paragraph("<b>2. DETAILED DATA</b>", styles['Heading2']))
            elements.append(Spacer(1, 10))
            
            if report_data.get('detailed_data'):
                detailed_data = report_data['detailed_data']
                
                # Add metadata about detailed records
                if report_data.get('metadata'):
                    metadata = report_data['metadata']
                    meta_text = f"<b>Total Records:</b> {json.dumps(metadata.get('total_records', {}), indent=2)}<br/>"
                    elements.append(Paragraph(meta_text, styles['Normal']))
                    elements.append(Spacer(1, 10))
                
                # Add detailed tables based on report type
                if report_type == 'admin_dashboard' and 'users' in detailed_data:
                    # Users Table
                    elements.append(Paragraph("<b>Users List</b>", styles['Heading3']))
                    users_data = [['ID', 'Employee No', 'Name', 'Email', 'Role', 'Status']]
                    for user_data in detailed_data['users'][:50]:  # Limit to first 50 for PDF
                        users_data.append([
                            user_data.get('id', ''),
                            user_data.get('emp_number', ''),
                            user_data.get('names', ''),
                            user_data.get('email', ''),
                            user_data.get('role', ''),
                            user_data.get('status', '')
                        ])
                    
                    if len(users_data) > 1:
                        users_table = Table(users_data, colWidths=[0.5*inch, 1*inch, 1.5*inch, 2*inch, 1*inch, 1*inch])
                        users_table.setStyle(TableStyle([
                            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#28B463')),
                            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                            ('FONTSIZE', (0, 0), (-1, -1), 8),
                            ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
                            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
                            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F9F9F9')])
                        ]))
                        elements.append(users_table)
                        elements.append(Spacer(1, 10))
                        
                        if len(detailed_data['users']) > 50:
                            elements.append(Paragraph(
                                f"<i>Showing 50 of {len(detailed_data['users'])} users. Full data available in Excel export.</i>",
                                styles['Italic']
                            ))
                            elements.append(Spacer(1, 10))
                
                elif report_type == 'team_performance' and 'performance_details' in detailed_data:
                    # Team Performance Detailed Table
                    elements.append(Paragraph("<b>Team Performance Details</b>", styles['Heading3']))
                    
                    for idx, emp_data in enumerate(detailed_data['performance_details'][:20], 1):  # Limit to 20 employees
                        elements.append(Paragraph(f"<b>{idx}. {emp_data.get('employee', {}).get('names', '')}</b>", styles['Normal']))
                        
                        # Employee summary table
                        if 'summary' in emp_data:
                            summary = emp_data['summary']
                            emp_summary_data = [
                                ['Metric', 'Value'],
                                ['Employee Number', summary.get('employee_number', '')],
                                ['Shift', summary.get('shift', '')],
                                ['Break Completion', f"{summary.get('break_performance', {}).get('completion_rate', 0)}%"],
                                ['Task Completion', f"{summary.get('task_performance', {}).get('completion_rate', 0)}%"],
                                ['Attendance Rate', f"{summary.get('attendance', {}).get('attendance_rate', 0)}%"]
                            ]
                            
                            emp_table = Table(emp_summary_data, colWidths=[2*inch, 3*inch])
                            emp_table.setStyle(TableStyle([
                                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#7D3C98')),
                                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                                ('FONTSIZE', (0, 0), (-1, -1), 8),
                                ('BACKGROUND', (0, 1), (-1, -1), colors.white),
                                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                            ]))
                            elements.append(emp_table)
                            elements.append(Spacer(1, 5))
            
            # SECTION 3: FOOTER
            elements.append(Spacer(1, 30))
            footer_text = f"""
            <i>Report generated by {config.get('generated_by', 'System')} on {now().strftime('%Y-%m-%d %H:%M:%S')}<br/>
            This report contains both summary and detailed data for comprehensive analysis.</i>
            """
            elements.append(Paragraph(footer_text, styles['Italic']))
            
            # Build PDF
            doc.build(elements)
            
            # Get PDF content
            pdf_content = buffer.getvalue()
            buffer.close()
            
            return pdf_content
            
        except Exception as e:
            print(f"PDF Export Error: {str(e)}")
            raise
    
    @staticmethod
    def export_excel(report_type, report_data, filters, config, user):
        """Export report as Excel with both summary and detailed data"""
        try:
            # Create Excel writer
            output = BytesIO()
            with pd.ExcelWriter(output, engine='openpyxl') as writer:
                workbook = writer.book
                
                # SHEET 1: SUMMARY
                summary_sheet = workbook.create_sheet("Summary")
                
                # Write header
                summary_sheet.append(["REPORT SUMMARY"])
                summary_sheet.append([])
                
                # Write report info
                summary_sheet.append(["Organization:", config.get('organization', 'Employee Management System')])
                summary_sheet.append(["System:", config.get('system', 'Shift & Task Management System')])
                summary_sheet.append(["Generated By:", config.get('generated_by', user.names if hasattr(user, 'names') else 'System')])
                summary_sheet.append(["Generated At:", now().strftime('%Y-%m-%d %H:%M:%S')])
                summary_sheet.append(["Report Type:", report_type.replace('_', ' ').title()])
                summary_sheet.append(["Export Format:", "Excel"])
                summary_sheet.append([])
                
                # Write filters
                if filters:
                    summary_sheet.append(["FILTERS APPLIED:"])
                    for key, value in filters.items():
                        if value:
                            summary_sheet.append([f"- {key.replace('_', ' ').title()}:", value])
                    summary_sheet.append([])
                
                # Write summary data
                if report_data.get('summary'):
                    summary = report_data['summary']
                    summary_sheet.append(["SUMMARY DATA:"])
                    summary_sheet.append([])
                    
                    if report_type == 'admin_dashboard':
                        # Users Summary
                        summary_sheet.append(["USERS SUMMARY"])
                        users_summary = summary.get('users', {})
                        summary_sheet.append(["Total Users:", users_summary.get('total', 0)])
                        summary_sheet.append(["Active Users:", users_summary.get('active', 0)])
                        summary_sheet.append(["Supervisors:", users_summary.get('supervisors', 0)])
                        summary_sheet.append(["Employees:", users_summary.get('employees', 0)])
                        summary_sheet.append([])
                        
                        # Shifts Summary
                        summary_sheet.append(["SHIFTS SUMMARY"])
                        shifts_summary = summary.get('shifts', {})
                        summary_sheet.append(["Total Shifts:", shifts_summary.get('total', 0)])
                        summary_sheet.append(["Active Shifts:", shifts_summary.get('active', 0)])
                        summary_sheet.append(["Avg Users/Shift:", shifts_summary.get('average_users_per_shift', 0)])
                        summary_sheet.append([])
                        
                    elif report_type == 'team_performance':
                        summary_sheet.append(["TEAM PERFORMANCE SUMMARY"])
                        summary_sheet.append(["Supervisor:", summary.get('supervisor_name', '')])
                        summary_sheet.append(["Time Period:", summary.get('time_period', '')])
                        summary_sheet.append(["Total Employees:", summary.get('total_employees', 0)])
                        summary_sheet.append([])
                        
                        # Individual employee summaries
                        if 'team_performance' in summary:
                            summary_sheet.append(["INDIVIDUAL PERFORMANCE"])
                            summary_sheet.append(["Employee", "Break Comp %", "Task Comp %", "Attendance %"])
                            for emp in summary['team_performance']:
                                summary_sheet.append([
                                    emp.get('employee_name', ''),
                                    emp.get('break_performance', {}).get('completion_rate', 0),
                                    emp.get('task_performance', {}).get('completion_rate', 0),
                                    emp.get('attendance', {}).get('attendance_rate', 0)
                                ])
                
                # SHEET 2: DETAILED DATA
                if report_data.get('detailed_data'):
                    detailed_data = report_data['detailed_data']
                    detail_sheet = workbook.create_sheet("Detailed Data")
                    
                    detail_sheet.append(["DETAILED DATA"])
                    detail_sheet.append([])
                    
                    # Write metadata
                    if report_data.get('metadata'):
                        metadata = report_data['metadata']
                        detail_sheet.append(["METADATA"])
                        detail_sheet.append(["Generated At:", metadata.get('generated_at', now().strftime('%Y-%m-%d %H:%M:%S'))])
                        detail_sheet.append(["Generated By:", metadata.get('generated_by', '')])
                        detail_sheet.append(["Report Type:", metadata.get('report_type', '')])
                        detail_sheet.append(["Time Period:", metadata.get('time_period', '')])
                        detail_sheet.append([])
                        
                        # Total records
                        detail_sheet.append(["TOTAL RECORDS:"])
                        total_records = metadata.get('total_records', {})
                        for key, value in total_records.items():
                            detail_sheet.append([key.replace('_', ' ').title() + ":", value])
                        detail_sheet.append([])
                    
                    # Write detailed data based on report type
                    if report_type == 'admin_dashboard':
                        # Users Detailed Data
                        if 'users' in detailed_data:
                            detail_sheet.append(["USERS DETAILED DATA"])
                            detail_sheet.append([])
                            
                            # Convert to DataFrame
                            users_df = pd.DataFrame(detailed_data['users'])
                            users_df.to_excel(writer, sheet_name='Users Data', index=False)
                            
                            # Create a separate sheet for each data type if available
                            if 'shifts' in detailed_data and detailed_data['shifts']:
                                shifts_df = pd.DataFrame(detailed_data['shifts'])
                                shifts_df.to_excel(writer, sheet_name='Shifts Data', index=False)
                            
                            if 'tasks' in detailed_data and detailed_data['tasks']:
                                tasks_df = pd.DataFrame(detailed_data['tasks'])
                                tasks_df.to_excel(writer, sheet_name='Tasks Data', index=False)
                    
                    elif report_type == 'team_performance':
                        # Team Performance Detailed Data
                        if 'performance_details' in detailed_data:
                            detail_sheet.append(["TEAM PERFORMANCE DETAILS"])
                            detail_sheet.append([])
                            
                            # Create DataFrame for performance details
                            performance_rows = []
                            for emp_data in detailed_data['performance_details']:
                                emp = emp_data.get('employee', {})
                                summary = emp_data.get('summary', {})
                                
                                performance_rows.append({
                                    'Employee ID': emp.get('id', ''),
                                    'Employee Name': emp.get('names', ''),
                                    'Employee Number': emp.get('emp_number', ''),
                                    'Shift': emp.get('current_shift', ''),
                                    'Break Completion %': summary.get('break_performance', {}).get('completion_rate', 0),
                                    'Task Completion %': summary.get('task_performance', {}).get('completion_rate', 0),
                                    'Attendance %': summary.get('attendance', {}).get('attendance_rate', 0),
                                    'Total Breaks': summary.get('break_performance', {}).get('total', 0),
                                    'Total Tasks': summary.get('task_performance', {}).get('total', 0)
                                })
                            
                            if performance_rows:
                                perf_df = pd.DataFrame(performance_rows)
                                perf_df.to_excel(writer, sheet_name='Performance Data', index=False)
                            
                            # Individual employee sheets
                            for emp_data in detailed_data['performance_details'][:10]:  # Limit to 10 employees for file size
                                emp = emp_data.get('employee', {})
                                emp_name = emp.get('names', 'Employee').replace('/', '_').replace('\\', '_')[:31]
                                emp_sheet = workbook.create_sheet(f"{emp_name[:20]}...")
                                
                                # Employee info
                                emp_sheet.append(["EMPLOYEE INFORMATION"])
                                emp_sheet.append(["Name:", emp.get('names', '')])
                                emp_sheet.append(["Employee Number:", emp.get('emp_number', '')])
                                emp_sheet.append(["Email:", emp.get('email', '')])
                                emp_sheet.append(["Role:", emp.get('role', '')])
                                emp_sheet.append(["Shift:", emp.get('current_shift', '')])
                                emp_sheet.append([])
                                
                                # Breaks data
                                if 'breaks' in emp_data and emp_data['breaks']:
                                    emp_sheet.append(["BREAKS DATA"])
                                    breaks_df = pd.DataFrame(emp_data['breaks'])
                                    breaks_df.to_excel(writer, sheet_name=f"{emp_name[:15]}_Breaks")
                                
                                # Tasks data
                                if 'tasks' in emp_data and emp_data['tasks']:
                                    emp_sheet.append(["TASKS DATA"])
                                    tasks_df = pd.DataFrame(emp_data['tasks'])
                                    tasks_df.to_excel(writer, sheet_name=f"{emp_name[:15]}_Tasks")
            
            # Remove default sheet if it exists
            if 'Sheet' in workbook.sheetnames:
                del workbook['Sheet']
            
            # Auto-adjust column widths for all sheets
            for sheet_name in workbook.sheetnames:
                worksheet = workbook[sheet_name]
                for column in worksheet.columns:
                    max_length = 0
                    column_letter = column[0].column_letter
                    for cell in column:
                        try:
                            if len(str(cell.value)) > max_length:
                                max_length = len(str(cell.value))
                        except:
                            pass
                    adjusted_width = min(max_length + 2, 50)
                    worksheet.column_dimensions[column_letter].width = adjusted_width
            
            # Get Excel content
            excel_content = output.getvalue()
            output.close()
            
            return excel_content
            
        except Exception as e:
            print(f"Excel Export Error: {str(e)}")
            raise
    
    @staticmethod
    def export_csv(report_type, report_data, filters, config, user):
        """Export report as CSV with both summary and detailed data"""
        try:
            # Create StringIO buffer for CSV
            output = StringIO()
            writer = csv.writer(output)
            
            # SECTION 1: HEADER
            writer.writerow([f"{report_type.replace('_', ' ').title()} REPORT"])
            writer.writerow([])
            
            # Report Info
            writer.writerow(["REPORT INFORMATION"])
            writer.writerow(["Organization:", config.get('organization', 'Employee Management System')])
            writer.writerow(["System:", config.get('system', 'Shift & Task Management System')])
            writer.writerow(["Generated By:", config.get('generated_by', user.names if hasattr(user, 'names') else 'System')])
            writer.writerow(["Generated At:", now().strftime('%Y-%m-%d %H:%M:%S')])
            writer.writerow(["Report Type:", report_type.replace('_', ' ').title()])
            writer.writerow(["Export Format:", "CSV"])
            writer.writerow([])
            
            # Filters
            if filters:
                writer.writerow(["FILTERS APPLIED"])
                for key, value in filters.items():
                    if value:
                        writer.writerow([f"- {key.replace('_', ' ').title()}:", value])
                writer.writerow([])
            
            # SECTION 2: SUMMARY DATA
            writer.writerow(["SUMMARY DATA"])
            writer.writerow([])
            
            if report_data.get('summary'):
                summary = report_data['summary']
                
                if report_type == 'admin_dashboard':
                    writer.writerow(["USERS SUMMARY"])
                    users_summary = summary.get('users', {})
                    writer.writerow(["Total Users:", users_summary.get('total', 0)])
                    writer.writerow(["Active Users:", users_summary.get('active', 0)])
                    writer.writerow(["Supervisors:", users_summary.get('supervisors', 0)])
                    writer.writerow(["Employees:", users_summary.get('employees', 0)])
                    writer.writerow([])
                    
                    writer.writerow(["SHIFTS SUMMARY"])
                    shifts_summary = summary.get('shifts', {})
                    writer.writerow(["Total Shifts:", shifts_summary.get('total', 0)])
                    writer.writerow(["Active Shifts:", shifts_summary.get('active', 0)])
                    writer.writerow([])
                
                elif report_type == 'team_performance':
                    writer.writerow(["TEAM PERFORMANCE SUMMARY"])
                    writer.writerow(["Supervisor:", summary.get('supervisor_name', '')])
                    writer.writerow(["Time Period:", summary.get('time_period', '')])
                    writer.writerow(["Total Employees:", summary.get('total_employees', 0)])
                    writer.writerow([])
            
            writer.writerow([])
            
            # SECTION 3: DETAILED DATA
            writer.writerow(["DETAILED DATA"])
            writer.writerow([])
            
            if report_data.get('detailed_data'):
                detailed_data = report_data['detailed_data']
                
                # Metadata
                if report_data.get('metadata'):
                    metadata = report_data['metadata']
                    writer.writerow(["METADATA"])
                    writer.writerow(["Generated At:", metadata.get('generated_at', now().strftime('%Y-%m-%d %H:%M:%S'))])
                    writer.writerow(["Generated By:", metadata.get('generated_by', '')])
                    writer.writerow([])
                    
                    # Total records
                    writer.writerow(["TOTAL RECORDS"])
                    total_records = metadata.get('total_records', {})
                    for key, value in total_records.items():
                        writer.writerow([key.replace('_', ' ').title() + ":", value])
                    writer.writerow([])
                
                # Detailed data based on report type
                if report_type == 'admin_dashboard' and 'users' in detailed_data:
                    writer.writerow(["USERS DETAILED DATA"])
                    writer.writerow([])
                    
                    # Write headers
                    if detailed_data['users']:
                        headers = detailed_data['users'][0].keys()
                        writer.writerow(headers)
                        
                        # Write data rows (limit to 1000 for CSV)
                        for idx, user_data in enumerate(detailed_data['users'][:1000]):
                            writer.writerow([user_data.get(header, '') for header in headers])
                        
                        if len(detailed_data['users']) > 1000:
                            writer.writerow([])
                            writer.writerow([f"Showing 1000 of {len(detailed_data['users'])} records"])
                
                elif report_type == 'team_performance' and 'performance_details' in detailed_data:
                    writer.writerow(["TEAM PERFORMANCE DETAILS"])
                    writer.writerow([])
                    
                    # Write headers
                    headers = ["Employee Name", "Employee Number", "Shift", 
                              "Break Completion %", "Task Completion %", "Attendance %",
                              "Total Breaks", "Total Tasks"]
                    writer.writerow(headers)
                    
                    # Write data rows
                    for emp_data in detailed_data['performance_details']:
                        emp = emp_data.get('employee', {})
                        summary = emp_data.get('summary', {})
                        
                        writer.writerow([
                            emp.get('names', ''),
                            emp.get('emp_number', ''),
                            emp.get('current_shift', ''),
                            summary.get('break_performance', {}).get('completion_rate', 0),
                            summary.get('task_performance', {}).get('completion_rate', 0),
                            summary.get('attendance', {}).get('attendance_rate', 0),
                            summary.get('break_performance', {}).get('total', 0),
                            summary.get('task_performance', {}).get('total', 0)
                        ])
            
            # Get CSV content
            csv_content = output.getvalue()
            output.close()
            
            return csv_content
            
        except Exception as e:
            print(f"CSV Export Error: {str(e)}")
            raise