# Generated by Django 6.0.1 on 2026-01-28 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shiftApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('shift_only', 'Shift Only'), ('day_off_only', 'Day Off Only'), ('both', 'Both Shift and Day Off')], help_text='What is being requested to change', max_length=20)),
                ('reason', models.TextField(help_text='Reason for the change request')),
                ('current_day_off', models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('none', 'No Day Off')], help_text='Current day off of the employee', max_length=20, null=True)),
                ('new_day_off', models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('none', 'No Day Off')], help_text='Requested new day off', max_length=20, null=True)),
                ('start_date', models.DateField(help_text='Date when the change should take effect if accepted')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp when request was approved', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Timestamp when request was cancelled', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Exact time the request was sent')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Supervisor or admin who approved the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shift_requests', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='User who cancelled the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_shift_requests', to=settings.AUTH_USER_MODEL)),
                ('current_shift', models.ForeignKey(blank=True, help_text='Current shift of the employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_shift_requests', to='shiftApp.shift')),
                ('new_shift', models.ForeignKey(blank=True, help_text='Requested new shift', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_shift_requests', to='shiftApp.shift')),
                ('user', models.ForeignKey(help_text='Employee making the request', on_delete=django.db.models.deletion.CASCADE, related_name='shift_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shift Change Request',
                'verbose_name_plural': 'Shift Change Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='requestApp__user_id_4067d4_idx'), models.Index(fields=['status', 'created_at'], name='requestApp__status_0a74d6_idx'), models.Index(fields=['start_date'], name='requestApp__start_d_00d9b1_idx')],
            },
        ),
    ]
